version: 2.0

jobs:
  build:
    machine:
      image: ubuntu-2004:202008-01
    environment:
      DOCKER_IMAGE_NAME: albihasani94/threatfabric-challenge
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }} # appends cache key with a hash of pom.xml file
            - v1-dependencies- # fallback in case previous cache key is not found
      - run:
          name: Build the artifact
          command: mvn package
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}
      - run:
          name: Push to Docker registry
          command: |
            TAG=0.0.$CIRCLE_BUILD_NUM
            docker build -t $DOCKER_IMAGE_NAME:$TAG .
            echo "$DOCKER_PASS" | docker login --username $DOCKER_USER --password-stdin
            docker push $DOCKER_IMAGE_NAME:$TAG
            docker tag $DOCKER_IMAGE_NAME:$TAG $DOCKER_IMAGE_NAME:latest
            docker push $DOCKER_IMAGE_NAME:latest
  test:
    machine:
      image: ubuntu-2004:202008-01
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }} # appends cache key with a hash of pom.xml file
            - v1-dependencies- # fallback in case previous cache key is not found
      - run: mvn test
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}

workflows:
  version: 2

  build:
    jobs:
      - build:
          context:
            - docker-env
          filters:
            branches:
              only:
                - master
  test:
    jobs:
      - test:
          filters:
            branches:
              ignore:
                - master
