version: 2.0

jobs:
  build:
    machine:
      image: ubuntu-2004:202008-01
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }} # appends cache key with a hash of pom.xml file
            - v1-dependencies- # fallback in case previous cache key is not found
      - run: mvn clean package
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}
      - run: |
          TAG=0.0.$CIRCLE_BUILD_NUM
          docker build -t albihasani94/threatfabric-challenge:$TAG .
          echo "$DOCKER_PASS" | docker login --username $DOCKER_USER --password-stdin
          docker push albihasani94/threatfabric-challenge:$TAG

workflows:
  version: 2
  build:
    jobs:
      - build:
          context:
            - docker-env
