create table detection
(
    type      varchar(20) not null,
    id        bigint generated by default as identity primary key,
    time      bigint      not null,
    device_id uuid references device
);

create table detection_new
(
    detectionuuid uuid unique,
    name_of_app   varchar(255),
    type_of_app   varchar(255),
    id            bigint not null primary key references detection
);

create table detection_no_threats
(
    id bigint not null primary key references detection
);

create table detection_resolved
(
    id                bigint not null primary key references detection,
    earlier_detection uuid references detection_new (detectionuuid)
);
