create table if not exists detection
(
    id        bigint generated by default as identity primary key,
    time      bigint      ,--not null,
    device_id uuid references device,
    type      varchar(20) not null
);

create table if not exists  detection_new
(
    id             bigint not null primary key references detection,
    detection_uuid uuid unique,
    name_of_app    varchar(255),
    type_of_app    varchar(255)
);

create table if not exists  detection_no_threats
(
    id bigint not null primary key references detection
);

create table if not exists  detection_resolved
(
    id                bigint not null primary key references detection,
    earlier_detection uuid references detection_new (detection_uuid)
);
